services:
  mysql:
    image: mysql:8.0
    container_name: mysql_simulation
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pandapower_db
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d